// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProdutoAPI.Repository.DataBase_Produto;

namespace ProdutoAPI.Repository.Migrations
{
    [DbContext(typeof(DB_Produto))]
    partial class DB_ProdutoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("ApiProduto.Models.Produto", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("nome")
                        .HasMaxLength(5)
                        .HasColumnType("char(5) CHARACTER SET utf8mb4");

                    b.Property<int>("qtd")
                        .HasColumnType("int");

                    b.Property<double>("valunit")
                        .HasPrecision(3, 2)
                        .HasColumnType("double");

                    b.HasKey("id");

                    b.ToTable("Produtos");
                });
#pragma warning restore 612, 618
        }
    }
}
